sudo: false

language: php

php:
  - "7"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"

  
  - wget https://phar.phpunit.de/phpunit-5.7.phar
  
script: php phpunit-5.7.phar --bootstrap PodioAPI.php tests

notifications:
  email: false
